global:
  log_level: debug
client:
  interfaces:
    - name: enp0s3
  host: 127.0.0.1
  port: 50052
  transport_converter:
    host: 192.168.56.106
    port: 50051
server:
  host: 192.168.56.106
  port: 50051